### ISSUE TITLE
Ldap sync and test ldap login fail

### ISSUE THREAD

**Issue by wallacengene** [go-ldap/ldap#167]
I'm trying to configure ldap test so that I can import users from ad but it fails.
The test ldap option works but the test ldap login doesn't as seen below;
![123](https://user-images.githubusercontent.com/39522819/40362743-f1509ec0-5dbc-11e8-959b-313c7080e8a9.PNG)

**Comment by Project0** [comment]
@wallacengene without logs and source code is hard to say what fails here as this is only the library behind your shiny UI (screenshot). Not sure which application you are using, but you should first get in touch with the vendor of this app.
Just a hint: Did you try to use the UPN instead of just the username (`username@domain.tld`)?
