### ISSUE TITLE
Proposal: Handle/Return Modify Response

### ISSUE THREAD

**Issue by jamesgoodhouse** [go-ldap/ldap#228]
Currently the result for an LDAP modify is not used (with the exception of debugging). There are use cases in need of the result, such as Pre/Post-Read controls as well as other types of Controls. I am proposing that the signature for LDAP modify be changed to something like:

```go
// ModifyResult holds the server's response to a modify request
type ModifyResult struct {
	// Controls are the returned controls
	Controls []Control
}

func (l *Conn) Modify(modifyRequest *ModifyRequest) (*ModifyResult, error)
```

This will require an update to the `Client` interface defined in `client.go`.

**Comment by jamesgoodhouse** [comment]
An alternative to this, since changing Modify's signature will be a breaking change, is to add a secondary method. Something like:

`func (l *Conn) ModifyWithResult(modifyRequest *ModifyRequest) (*ModifyResult, error)`

**Comment by stefanmcshane** [comment]
Hi @jamesgoodhouse,
I appreciate that this is a little later than hoped for, but I reworked the code you submitted for this so that its mergable and will hopefully be able to release within the week.
Check out the above PR to see if it works for your usecase if youre still having the issue.

Thanks,
Stefan
