### ISSUE TITLE
Send encoded base64 to server

### ISSUE THREAD

**Issue by raianfs** [go-ldap/ldap#322]
Hello, 

is there a way to send base64 encoded data as attributes? On LDIF files, it's done using : before the value.
Using this format or sending the data encoded, the server get the attribute as a string and use it as real value.

**Comment by xNevo** [comment]
@raianfs 
> Using this format or sending the data encoded, the server get the attribute as a string and use it as real value.

LDIF stores entries in Base64 for formatting purposes, since entries with raw bytes or with certain special characters may conflict with the specification. LDAP clients like ldapsearch, ldapmodify e.g. recognize this format, read it in and decode it back from Base64 to send it to the server

Quote from [ldap.com](https://ldap.com/ldif-the-ldap-data-interchange-format/):
> LDIF is a text-based representation of LDAP data, but sometimes raw LDAP data can’t be directly represented as text (e.g., if the value of an attribute includes bytes that don’t represent any character in the UTF-8 character set). At other times, the direct textual representation of LDAP data could conflict with the LDIF syntax in a way that would make it possible to unambiguously determine what the data actually is. It is therefore necessary to have some means of clearly and easily representing raw data in a manner that will not conflict with the structure used to encode data in LDIF. 

Quote from [Wikipedia](https://en.wikipedia.org/wiki/LDAP_Data_Interchange_Format#Content_record_format):
> Value data that do not fit within a portable subset of ASCII characters are marked with '::' after the attribute name and encoded into ASCII using base64 encoding

If you still want to send or read base64 encoded data, then Golang has already a package for this:
```go
package main

import (
	"encoding/base64"
	"fmt"
	"github.com/go-ldap/ldap/v3"
)

func main() {
	conn, _ := ldap.Dial("", "")
	result, _ := conn.Search(...)

	// for better readability, save the value in a variable
	rawValue := result.Entries[0].GetRawAttributeValue("base64EncodedAttribute")

	// create a simple buffer with the calculated length of the decoded string as size
	buff := make([]byte, base64.StdEncoding.DecodedLen(len(rawValue)))

	// decode the value and save it to the buffer
	decodedValue, err := base64.StdEncoding.Decode(buff, rawValue)
	if err != nil {
		// ...
	}
	fmt.Println(string(decodedValue))
}
```

**Comment by raianfs** [comment]
Hello @xNevo,

I had a wrong understanding about the data transfer to server. I was believing that the data was sent to server using base64, and the server should decode the data. 
Reading the LDAP Protocol RFC I saw that the attributes are all OCTET STRINGs, and how said by you, decode is the work for LDIF.

Tks by the teaching.
