### ISSUE TITLE
请问下，是没办法 move entry ？

### ISSUE THREAD

**Issue by zdwork** [go-ldap/ldap#339]

**Comment by cpuschma** [comment]
From putting your text in Google Translate, I suspect you're asking how to move an entry. Please see `NewModifyDNRequest` and the `NewSuperior` attribute of the modify requests: https://github.com/go-ldap/ldap/blob/8c6415ac9035d0ac34cfcc0422cd8dafae92d6d0/v3/moddn.go#L17-L36

Since you didn't ask or comment on this issue again I suspect you got your head around this yourself. Please use English language for future issues and describe exactly what is your problem with the library :)
