### ISSUE TITLE
pwdMaxAge and pwdMinAge not returned in Ldap search

### ISSUE THREAD

**Issue by avi94** [go-ldap/ldap#350]
We are trying to get the pwdMaxAge and pwdMinAge attributes returned in a search.

Following is the code:

`
filter := "(|"
	if searchParams.CN != nil {
		filter = filter + "(cn=" + *searchParams.CN + ")"
	}
	if searchParams.SAMAccountName != nil {
		filter = filter + "(sAMAccountName=" + *searchParams.SAMAccountName + ")"
	}
	if searchParams.UserPrincipalName != nil {
		filter = filter + "(userAccountControl=" + *searchParams.UserPrincipalName + ")"
	}
	filter = filter + ")"
	searchRequest := ldap.NewSearchRequest(
		baseDN, // The base dn to search
		ldap.ScopeWholeSubtree, ldap.NeverDerefAliases, 0, 0, false,
		filter, // The filter to apply
		[]string{"pwdMaxAge", "pwdMinAge", "unicodePwd", "objectClass", "whenChanged", "whenCreated", "userAccountControl", "dn", "cn", "sn", "sAMAccountName", "givenName", "mail", "lockoutTime", "pwdLastSet", "accountExpires"}, // A list attributes to retrieve
		nil,
	)

	s, errSearch := lConn.SearchWithPaging(searchRequest, math.MaxInt32)
	if errSearch != nil {
		log.Println("ldapSearch: " + errSearch.Error())
	}
`

Now the issue is, the attributes are not returned at all. Below is a console log of the attributes we are fetching that I can share here:

pwdMaxAge: , pwdMinAge: , whenChanged: 20211223061858.0Z unicodePwd:  userPassword:  userAccountControl: 512 objectClass: top  Username: carolin whenCreated: 20191018100730.0Z lockoutTime: 0 pwdLastSet: 0 accountExpires: 0 

All the other attributes I tried to fetch above in the code is being fetched. Only pwdMaxAge and pwdMinAge cannot be fetched for some reason.

Can someone please help? Thanks in advance!

**Comment by xNevo** [comment]
It seems you're using Active Directory as your directory service of choice. I just spun of my Windows Server VM and checked, but even with "Advanced Features" enabled in DSA, I couldn't find the attributes you're trying to query, even with "Constructed", "Backlinks" and "System-only" filters enabled:

![image](https://user-images.githubusercontent.com/16116826/147352688-b19fe883-e717-4a7b-843e-e12bc37a8a88.png)

**Comment by avi94** [comment]
Yes we are using Active Directory. But is there a major difference between the attributes of Ldap and the attributes of AD?

**Comment by xNevo** [comment]
LDAP is just the protocol, Active Directory is the implementation from Microsoft, just like OpenLDAP and others, but the implementation details may vary heavily (especially when it comes to schemas).

From what I can tell, `pwdMinAge` and `pwdMaxAge` is not queryable through search requests in the AD forest and are not part of any default user objectClass´es (top, organizationalPerson, person, user). I also suspected that the attributes might be only available to priviliged accounts due to ACLs, but even with full Administrator privileges I couldn't find the attributes `pwdMinage` and `pwdMaxAge`

![image](https://user-images.githubusercontent.com/16116826/147372219-22cfac43-7ed8-4df8-8baf-1f17dd090515.png)

I don't know if these informations might be available in `Configuraton` in `CN=Configuration,DC=your,DC=domain,DC=here`. Anyway, the library doesn't differentiate between different attributes, so I'm pretty sure it's atleast not a go-ldap problem.

**Comment by cpuschma** [comment]
@avi94 Any new informations on this, or can we close this issue?

**Comment by avi94** [comment]
@cpuschma Sure, close the issue. I could not get the attributes returned, even though upon checking with the Windows team at the organisation level, we did find these attributes present. Still couldn't fetch them, for what reason no one knows.
