### ISSUE TITLE
Fix Go 1.9 and earlier tests

### ISSUE THREAD

**Issue by johnweldon** [go-ldap/ldap#353]
Dependency on github.com/Azure/go-ntlmssp should either be pinned to a passing version, or we decide if we want to drop testing for pre-1.10 versions?  I'd prefer the former option.  ( See discussion on #352  )

**Comment by xNevo** [comment]
Personally, I'd prefer the latter one as well. Also, since the last release of go1.10.x, multiple security patches + fixes have been applied to the std libs. For example:

* https://github.com/golang/go/commit/c1d9ca70995dc232a2145e3214f94e03409f6fcc
* https://github.com/golang/go/commit/d497d80d23bf83765316b274885257ac66d54bb7
* https://github.com/golang/go/commit/44bb3b4b5341f5bb373acb0b8130795f888c9ace

**Comment by johnweldon** [comment]
Okay, let's drop support for Go 1.9 and earlier.

**Comment by xNevo** [comment]
I suggest v1.13, since [go-asn1-ber uses this version as well](https://github.com/go-asn1-ber/asn1-ber/blob/158c9f99fc9c29a5ca9203be28f0fdf31cfb9701/go.mod)

**Comment by johnweldon** [comment]
I thought I'd responded to this... sorry... yes I'm okay with v1.13+
