### ISSUE TITLE
help: problems encountered in changing passwords

### ISSUE THREAD

**Issue by songzhibin97** [go-ldap/ldap#359]
Use ldap.DialURL and ldaps links and try to change the password, do not skip the security verification error "LDAP Result Code 200" Network Error ": x509: certificate signed by unknown authority", skip the security verification error "LDAP Result Code 2" Protocol Error ": 0000203D: LdapErr: DSID-0C0911AA, comment: Unknown extended request OID, data 0, v3839", hope to get help, thank you

**Comment by cpuschma** [comment]
Sorry for the delayed response. This seems like a duplicate of #106. See also this thread on reddit, indicating that this might be because of missing encoding of the new password: https://www.reddit.com/r/golang/comments/csh2ps/ldap_v3_password_reset_error/

Can you maybe post the source code where you prepare and submit the password modify request, @songzhibin97 ?

**Comment by songzhibin97** [comment]
Thank you for your reply. I seem to have tried this method, and it doesn't work. I'm still trying to find other ways.

**Comment by liu-cn** [comment]
彬哥，我也遇到这个问题了，不清楚是不是因为连接时候没用ldaps://协议？不知道你后来有没有解决
