### ISSUE TITLE
Unable to get correct value for "pwdLastSet" attribute

### ISSUE THREAD

**Issue by ccunninghame** [go-ldap/ldap#396]
When inspecting the attribute with the "Active Directory Users and Computers" gui, the user I am testing on has a pwdLastSet value of "132986563876467372". That same value gets returned when I query for the user with powershell.

go-ldap returns the attribute as: &{pwdLastSet [133090795866132342] [[49 51 51 48 57 48 55 57 53 56 54 54 49 51 50 51 52 50]]}

Is there a setting that I am missing on the NewSearchRequest function for it to return properly?

**Comment by cpuschma** [comment]
This is due to the GUI and Powershell converting the timestamp seamlessly. When inspecting an object using any generic LDAP Explorer (like LdapAdmin), you'll see that the attribute is actually numeric:

![grafik](https://user-images.githubusercontent.com/16116826/194558327-e120f778-e2ac-4e60-9efc-b48cd03ede86.png)

See https://www.php.net/manual/de/function.ldap-get-entries.php#33180 on how to convert the Windows FILETIME timestamp into UNIX epoch. From there on, you can use `time.Unix(convertedTimestamp, 0)` to get the date and time.

**Comment by ccunninghame** [comment]
Thank you for the quick reply and I apologizing for wasting your time. After spending all yesterday on this, it turns out that our testing AD had been re-seeded, so the AD and go-ldap results that I was comparing were from two different datasets.

The "133090795866132342" value being returned is correct and matches what I can see now in the gui.
