### ISSUE TITLE
Request to add ldapctl tools to the go-ldap organization

### ISSUE THREAD

**Issue by eryajf** [go-ldap/ldap#404]
I have noticed that many people still have doubts about the specific usage of some methods when using go-ldap. In fact, I have encountered such confusion in the process of using this library. Therefore, I wrote a [ldapctl](https://github.com/eryajf/ldapctl) tool to integrate go-ldap methods into the project in a practical way to help later users to quickly use go-ldap the library.

If possible, I hope this tool can be displayed here in go-ldap in a suitable way to help more people.

Therefore, I apply to incorporate ldapctl project into go-ldap organization. If you have any questions, please let me know at any time.

**Comment by johnweldon** [comment]
I think is the same request that you closed back in June? #377 

I'm not opposed to suggesting that project as an example code base, but I'm not taking the time right now to evaluate that project to decide whether to include it.

@go-ldap/committers - any thoughts?

**Comment by cpuschma** [comment]
The repository seem to be abandoned (last commit is from 2y ago). Most of the documentation and commit messages are either incomplete or what seems to be chinese. 

I appreciate the effort, but because of the reasons mentioned above and other missing features to other multi-tools like ldapmodify or ldapsearch I would decline the request.
