### ISSUE TITLE
Impossible to read all the LDAP Tree

### ISSUE THREAD

**Issue by michele-deluca** [go-ldap/ldap#410]
Hi, 
I am trying to read all the ldap tree to make a copy into a external database.
Now it is impossible to make this operation because the ldap search procedure load all the result to a slice before returning its. 
In this case we have two issue:

1. the slice size is important and the memory used by the process grows and the VM crash because not have sufficient memory.
2. the elaboration time grows because we need first to load all the result into a slice and then read it one by one.

it is possible to read the results as they are generated without loading them in the list and then scrolling through it?

**Comment by cpuschma** [comment]
There are two limiting factors that complicate the whole process:
- If the tree is large, the directory server may abort the request because of the size limit.
- The data is first held between `Search` and `SearchWithPaging` and not successively transmitted like channels. For this however drafts already exist and are discussed.

I can only recommend that you instead work your way down the tree with multiple search requests to not exceed the SizeLimit in both cases.

**Comment by cpuschma** [comment]
Async search has been implemented in the latest releases. I think this issue can be safely closed.
