### ISSUE TITLE
3.4.5 has breaking API changes from 3.4.4

### ISSUE THREAD

**Issue by natefinch** [go-ldap/ldap#463]
This PR https://github.com/go-ldap/ldap/pull/433 changed the [signature of Conn's Close](https://github.com/go-ldap/ldap/pull/433/files#diff-4f427d2b022907c552328e63f137561f6de92396d7a6e8f6c2ea1bcf0db52654L280-R282) method to add an error to the return value. This is a breaking API change that should not have been made in a patch release.

We use this in some of our services at GitHub, and it makes confusing error messages and extra work for us when a patch version update of a dependency suddenly causes compiler errors.

It's not *super* hard to adjust callers to the new signature, but I hope the authors of this library will be more careful about such changes in the future. API signatures should not be changed willy-nilly.

**Comment by johnweldon** [comment]
Hi @natefinch - long time no talk :)

You're right; I missed that in this MR - I've tried to be careful about breaking API changes, but this slipped by.

Thanks for raising this.

(//cc @go-ldap/committers )

**Comment by cpuschma** [comment]
The fact that the PR has adapted the signature of the function is correct, when considering the possible impact and benefit was weighed. The goal was to give the programmer the possibility to know that the call `Close` worked. In the implementation at that time there would have been a panic and a recover in the library without any feedback to the programmer, the message would have gone directly to the console.

Code that looks like this:
```
func main() {
	conn, _ := ldap.DialURL("ldap://localhost:389")
	_ = conn.Bind("test@localhost", "123456")
	defer conn.Close()
	
	searchResult, err := conn.Search(...)
	if err != nil {
		log.Fatalln(err)
	}
	fmt.Println(searchResult.Entries)
}
```

will still work, but linters will indicate that an error is returned if the library in go.mod is updated. On 2022-04-21 in #372 the minimum Go version was raised to 1.14 (see @johnweldon's comment https://github.com/go-ldap/ldap/pull/367#issuecomment-1089604708), which already has support for Go Modules in the format known today. So unless you explicitly use "go get -u" to update the library, the impact of this should be small. Additionally, since you wrote that this was done in a minor release: The go-ldap project is not really the most active one, also because the LDAP standard has changed little to nothing for about 10 years. I see the chances that we will ever make a new major release as extremely low to implement breaking changes, also because the decision to take the major release level "3" was due to the fact that the LDAPv3 standard is supported.

Nevertheless, you're right, changes to the signature should be avoided and kept to an absolute minimum if necessary.
