### ISSUE TITLE
Provision to check if connection is still alive or not

### ISSUE THREAD

**Issue by svigne1** [go-ldap/ldap#96]
Hi,
I want a way to figure out whether an ldap connection i created has been closed or not.
I see that `Conn` struct has a bool [`isClosing`](https://github.com/go-ldap/ldap/blob/master/conn.go#L85) to gain that info. But it is private. 
Can you expose a public function which value of `isClosing`??

Right now, Whenever i receive an error, I simply retry the search query after restarting the connection.
My use case is,
I am exposing a web service, which uses ldap. For better performance, i created the ldap connection beforehand and kept reusing it for each request.

If i had a way to know whether the connection is lost or not, it would make it simpler for me.
Thanks You

**Comment by liggitt** [comment]
Even if you had a way to check, you would still need to handle a connection closed error, since the connection could have closed between the time you checked and when you used it (even if that time was very short). I think it would make more sense to return an error when you try to use a closed connection that makes it clear the operation never hit the network because the connection was closed, and you can use that to trigger opening a new connection and retrying

**Comment by svigne1** [comment]
Hi @liggitt  I never thought of that use case. The connection getting closed between the time i check and the time i use it. Super awesome point! Thank you for explaining it to me. 

I guess, giving out a provision or exposing `isClosing` is a bad idea then. Since a lot of people like me, not having thought of this edge case, would write bad code. 

You can close this issue. Thanks for correcting me :)

**Comment by dray92** [comment]
> Even if you had a way to check, you would still need to handle a connection closed error, since the connection could have closed between the time you checked and when you used it (even if that time was very short).

@liggitt - Yes, while that argument makes sense, I don't see why we can't export an `isClosed()` function for a proactive call to `Start()`. Yes, a reactive solution exists, but why not enable proactive actions?
